spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rivals_db
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: create-drop
    show-sql: true
    properties.hibernate.format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output.ansi.enabled: always
